# Generated by Django 4.0.4 on 2022-05-17 20:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=254)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
